os:
  - linux

env:
  global:
  - PGVERSION=9.5
  - PG_PRELOAD=decoding_json

language: node_js
node_js:
  - "4.0"

notifications:
  email:
    - jeffreymealo@gmail.com

before_install:
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update -qq
  - sudo update-alternatives --remove-all postmaster.1.gz
  - git clone --depth 1 https://gist.github.com/9963879.git tools
  - tools/nuke_pg.sh

install:
  - tools/install_pg.sh

before_script:
  - sudo bash -c "cat test/config/my.cnf >> /etc/mysql/my.cnf"
  - sudo bash -c "cat test/config/pg-hba.conf >> /etc/postgresql/$PGVERSION/main/pg-hba.conf"
  - sudo bash -c "cat test/config/postgresql.conf >> /etc/postgresql/$PGVERSION/main/postgresql.conf"
  - sudo service mysql stop
  - sudo service postgresql stop
  - git clone https://github.com/leptonix/decoding-json.git
  - cd decoding-json/
  - make
  - sudo make install
  - sudo service postgresql start
  - sudo pg_createcluster $PGVERSION test -p 55435 -u `whoami`
  - sudo pg_ctlcluster $PGVERSION test start
  - sudo service mysql start
  - sudo service mysql status
  - sudo su postgres -c "psql -h 127.0.0.1 -p 55435 -c \"CREATE ROLE lapidus PASSWORD '2PQM9aiKMJX5chv76gYdFJNi' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;\""
  - sudo su postgres -c "psql -h 127.0.0.1 -p 55435 -c 'CREATE DATABASE lapidus OWNER lapidus;'"
  - mysql -e "CREATE USER 'lapidus'@'localhost' IDENTIFIED BY '2PQM9aiKMJX5chv76gYdFJNi';" -uroot
  - mysql -e "GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'lapidus'@'localhost'" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot

script: "npm run-script test-travis"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
