os:
  - linux

env:
  global:
  - PGVERSION=9.5

language: node_js
node_js:
  - "4.0"

notifications:
  email:
    - jeffreymealo@gmail.com

before_install:
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update -qq
  - sudo update-alternatives --remove-all postmaster.1.gz
  - sudo service postgresql stop
  - sudo apt-get remove -y postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-common postgresql-contrib
  - sudo apt-get purge -y postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-common postgresql-contrib
  - sudo rm -rf /etc/postgresql
  - sudo rm -rf /var/lib/postgresql

install:
  - sudo apt-get install -y postgresql-common postgresql-$PGVERSION postgresql-client-$PGVERSION  postgresql-contrib-$PGVERSION postgresql-server-dev-$PGVERSION

before_script:
  - sudo bash -c "cat test/config/bin-log.cnf >> /etc/mysql/conf.d/bin-log.cnf"
  - sudo bash -c "cat test/config/pg_hba.conf > /etc/postgresql/$PGVERSION/main/pg_hba.conf"
  - sudo bash -c "cat test/config/postgresql.conf >> /etc/postgresql/$PGVERSION/main/postgresql.conf"
  - sudo bash -c "cat test/config/redis.conf >> /etc/redis/redis.conf"
  - sudo service redis-server start
  - mkdir the_hatch
  - mongod --port 27017 --dbpath the_hatch --replSet rs0 --oplogSize 20 --noprealloc --fork --smallfiles --logpath mongodb.log
  - sleep 5
  - mongo lapidus --eval 'printjson(rs.initiate());'
  - sleep 20
  - mongo lapidus --eval 'db.getMongo().setSlaveOk();'
  - mongo lapidus --eval 'db.createUser({ user: "lapidus", pwd: "2PQM9aiKMJX5chv76gYdFJNi", roles: [ {role: "clusterAdmin", db: "admin" }, { role: "readAnyDatabase", db: "admin" }, "readWrite" ] });'
  - sudo service mysql stop
  - sudo service postgresql stop
  - git clone https://github.com/leptonix/decoding-json.git
  - cd decoding-json/
  - make
  - sudo make install
  - cd ..
  - sudo service postgresql start
  - sudo service mysql start
  - sudo service mysql status
  - sudo service postgresql status
  - sudo su postgres -c "psql -c \"CREATE ROLE lapidus PASSWORD '2PQM9aiKMJX5chv76gYdFJNi' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;\""
  - sudo su postgres -c "psql -c 'CREATE DATABASE lapidus OWNER lapidus;'"
  - sudo su postgres -c "psql -c \"CREATE ROLE hurley PASSWORD '2PQM9aiKMJX5chv76gYdFJNi' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;\""
  - sudo su postgres -c "psql -c 'CREATE DATABASE hurley OWNER hurley;'"
  - mysql -e "CREATE DATABASE jacob;" -uroot
  - mysql -e "CREATE DATABASE sawyer;" -uroot
  - mysql -u root jacob < test/sql/test_table.sql
  - mysql -u root sawyer < test/sql/test_table.sql
  - mysql -e "CREATE USER 'jacob'@'localhost' IDENTIFIED BY '2PQM9aiKMJX5chv76gYdFJNi';" -uroot
  - mysql -e "CREATE USER 'sawyer'@'localhost' IDENTIFIED BY '2PQM9aiKMJX5chv76gYdFJNi';" -uroot
  - mysql -e "GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'jacob'@'localhost';" -uroot
  - mysql -e "GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'sawyer'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - npm install

script: "npm run-script test-travis"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
