os:
  - linux

addons:
  postgresql: "9.4"

env:
  global:
  - PGVERSION=9.5

language: node_js
node_js:
  - "4.0"

notifications:
  email:
    - jeffreymealo@gmail.com

before_install:
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update -qq
  - sudo update-alternatives --remove-all postmaster.1.gz
  - sudo service postgresql stop

install:
  - sudo apt-get install -y postgresql-$PGVERSION postgresql-client-$PGVERSION  postgresql-contrib-$PGVERSION postgresql-server-dev-$PGVERSION

before_script:
  - sudo bash -c "cat test/config/my.cnf >> /etc/mysql/my.cnf"
  - sudo bash -c "cat test/config/pg-hba.conf >> /etc/postgresql/$PGVERSION/main/pg-hba.conf"
  - sudo bash -c "cat test/config/postgresql.conf >> /etc/postgresql/$PGVERSION/main/postgresql.conf"
  - sudo service mysql stop
  - sudo service postgresql stop
  - git clone https://github.com/leptonix/decoding-json.git
  - cd decoding-json/
  - make
  - sudo make install
  - cd ..
  - sudo service postgresql start
  - sudo service mysql start
  - sudo service mysql status
  - sudo su postgres -c "psql -c \"CREATE ROLE lapidus PASSWORD '2PQM9aiKMJX5chv76gYdFJNi' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;\""
  - sudo su postgres -c "psql -c 'CREATE DATABASE lapidus OWNER lapidus;'"
  - mysql -e "CREATE USER 'lapidus'@'localhost' IDENTIFIED BY '2PQM9aiKMJX5chv76gYdFJNi';" -uroot
  - mysql -e "GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'lapidus'@'localhost'" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - npm install

script: "npm run-script test-travis"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
